apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bolt-payment-gateway-backend-config-staging
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
    port: 4000
  timeoutSec: 30